export const jogosTime = [
  {
    timeCasa: "Grêmio",
    timeVisitante: "Atlético-MG",
    data: "29/03/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports", "paramount-plus"],
  },
  {
    timeCasa: "Ceará",
    timeVisitante: "Grêmio",
    data: "06/04/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "espn"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Flamengo",
    data: "13/04/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "tnt-sports"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Grêmio",
    data: "16/04/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "globo"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Internacional",
    data: "19/04/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "cazetv"],
  },
  {
    timeCasa: "Vitória",
    timeVisitante: "Grêmio",
    data: "27/04/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "sportv"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Santos",
    data: "03/05/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "globo"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Bragantino",
    data: "11/05/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "disney-plus"],
  },
  {
    timeCasa: "São Paulo",
    timeVisitante: "Grêmio",
    data: "17/05/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "sbt"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Bahia",
    data: "24/05/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports"],
  },
  {
    timeCasa: "Juventude",
    timeVisitante: "Grêmio",
    data: "30/05/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "paramount-plus"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Corinthians",
    data: "12/06/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "cazetv"],
  },
  {
    timeCasa: "Cruzeiro",
    timeVisitante: "Grêmio",
    data: "13/07/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "paramount-plus"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Fortaleza",
    data: "17/07/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "sbt"],
  },
  {
    timeCasa: "Vasco",
    timeVisitante: "Grêmio",
    data: "19/07/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "cazetv"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Botafogo",
    data: "24/07/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "youtube"],
  },
  {
    timeCasa: "Palmeiras",
    timeVisitante: "Grêmio",
    data: "28/07/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "globo"],
  },
  {
    timeCasa: "Fluminense",
    timeVisitante: "Grêmio",
    data: "03/08/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "cazetv"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Sport",
    data: "09/08/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "sbt"],
  },
  {
    timeCasa: "Atlético-MG",
    timeVisitante: "Grêmio",
    data: "17/08/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "paramount-plus"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Ceará",
    data: "24/08/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "espn"],
  },
  {
    timeCasa: "Flamengo",
    timeVisitante: "Grêmio",
    data: "31/08/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["cazetv", "tnt-sports"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Mirassol",
    data: "13/09/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "paramount-plus"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Grêmio",
    data: "21/09/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "espn"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Vitória",
    data: "29/09/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "sbt"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Grêmio",
    data: "01/10/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "disney-plus"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Bragantino",
    data: "17/10/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "paramount-plus"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Bahia",
    data: "05/11/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "tnt-sports"],
  },
  {
    timeCasa: "Juventude",
    timeVisitante: "Grêmio",
    data: "19/11/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["youtube", "espn"],
  },
  {
    timeCasa: "Corinthians",
    timeVisitante: "Grêmio",
    data: "22/11/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "sbt"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Cruzeiro",
    data: "30/11/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "espn"],
  },
  {
    timeCasa: "Fortaleza",
    timeVisitante: "Grêmio",
    data: "03/12/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "cazetv"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Vasco",
    data: "06/12/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "sbt"],
  },
  {
    timeCasa: "Botafogo",
    timeVisitante: "Grêmio",
    data: "10/12/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Palmeiras",
    data: "13/12/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "sbt"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Fluminense",
    data: "17/12/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "globo"],
  },
  {
    timeCasa: "Sport",
    timeVisitante: "Grêmio",
    data: "21/12/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "sportv"],
  },
];
