export const jogosTime = [
  {
    timeCasa: "Flamengo",
    timeVisitante: "Internacional",
    data: "30/03/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports", "sbt"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Cruzeiro",
    data: "06/04/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "sportv"],
  },
  {
    timeCasa: "Fortaleza",
    timeVisitante: "Internacional",
    data: "12/04/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "sbt"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Palmeiras",
    data: "16/04/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "tnt-sports"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Internacional",
    data: "19/04/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "sbt"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Juventude",
    data: "26/04/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "sportv"],
  },
  {
    timeCasa: "Corinthians",
    timeVisitante: "Internacional",
    data: "03/05/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "tnt-sports"],
  },
  {
    timeCasa: "Botafogo",
    timeVisitante: "Internacional",
    data: "10/05/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "disney-plus"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Mirassol",
    data: "17/05/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "sportv"],
  },
  {
    timeCasa: "Sport",
    timeVisitante: "Internacional",
    data: "24/05/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Fluminense",
    data: "30/05/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "sbt"],
  },
  {
    timeCasa: "Atlético-MG",
    timeVisitante: "Internacional",
    data: "12/06/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "youtube"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Vitória",
    data: "13/07/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "paramount-plus"],
  },
  {
    timeCasa: "Bahia",
    timeVisitante: "Internacional",
    data: "16/07/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "sbt"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Ceará",
    data: "19/07/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "globo"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Internacional",
    data: "23/07/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "disney-plus"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Vasco",
    data: "26/07/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "paramount-plus"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "São Paulo",
    data: "02/08/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "globo"],
  },
  {
    timeCasa: "Bragantino",
    timeVisitante: "Internacional",
    data: "16/08/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "espn"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Flamengo",
    data: "23/08/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "globo"],
  },
  {
    timeCasa: "Cruzeiro",
    timeVisitante: "Internacional",
    data: "30/08/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "sbt"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Fortaleza",
    data: "13/09/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "sportv"],
  },
  {
    timeCasa: "Palmeiras",
    timeVisitante: "Internacional",
    data: "20/09/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "cazetv"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Grêmio",
    data: "27/09/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "tnt-sports"],
  },
  {
    timeCasa: "Juventude",
    timeVisitante: "Internacional",
    data: "01/10/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "disney-plus"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Corinthians",
    data: "16/10/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "sportv"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Botafogo",
    data: "25/10/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "espn"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Sport",
    data: "05/11/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "tnt-sports"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "São Paulo",
    data: "19/11/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "cazetv"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Atlético-MG",
    data: "22/11/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "sbt"],
  },
  {
    timeCasa: "Vitória",
    timeVisitante: "Internacional",
    data: "29/11/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "espn"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Bahia",
    data: "03/12/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["cazetv", "globo"],
  },
  {
    timeCasa: "Ceará",
    timeVisitante: "Internacional",
    data: "06/12/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "paramount-plus"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Santos",
    data: "13/12/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "globo"],
  },
  {
    timeCasa: "Vasco",
    timeVisitante: "Internacional",
    data: "17/12/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "espn"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "São Paulo",
    data: "21/12/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "youtube"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Bragantino",
    data: "21/12/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "sportv"],
  },
];
