export const jogosTime = [
  {
    timeCasa: "Cruzeiro",
    timeVisitante: "Mirassol",
    data: "30/03/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "record", "prime-video"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Fortaleza",
    data: "07/04/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "sbt"],
  },
  {
    timeCasa: "Bahia",
    timeVisitante: "Mirassol",
    data: "12/04/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "cazetv"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Grêmio",
    data: "17/04/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "youtube", "sportv"],
  },
  {
    timeCasa: "Juventude",
    timeVisitante: "Mirassol",
    data: "19/04/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["disney-plus", "premiere"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Atlético-MG",
    data: "27/04/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "record"],
  },
  {
    timeCasa: "Bragantino",
    timeVisitante: "Mirassol",
    data: "03/05/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "youtube", "espn"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Corinthians",
    data: "12/05/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "band", "premiere"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Mirassol",
    data: "18/05/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "espn"],
  },
  {
    timeCasa: "São Paulo",
    timeVisitante: "Mirassol",
    data: "25/05/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["cazetv", "prime-video", "goat"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Sport",
    data: "02/06/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["record", "sbt"],
  },
  {
    timeCasa: "Botafogo",
    timeVisitante: "Mirassol",
    data: "11/06/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "espn"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Fluminense",
    data: "13/07/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["youtube", "tnt-sports"],
  },
  {
    timeCasa: "Palmeiras",
    timeVisitante: "Mirassol",
    data: "17/07/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "disney-plus"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Santos",
    data: "21/07/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "band", "sportv"],
  },
  {
    timeCasa: "Ceará",
    timeVisitante: "Mirassol",
    data: "23/07/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["cazetv", "paramount-plus"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Vitória",
    data: "28/07/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["record", "youtube", "globo"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Vasco",
    data: "03/08/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "cazetv"],
  },
  {
    timeCasa: "Flamengo",
    timeVisitante: "Mirassol",
    data: "09/08/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports", "premiere"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Cruzeiro",
    data: "16/08/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "sbt"],
  },
  {
    timeCasa: "Fortaleza",
    timeVisitante: "Mirassol",
    data: "25/08/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Bahia",
    data: "31/08/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["disney-plus", "youtube"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Mirassol",
    data: "13/09/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "paramount-plus"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Juventude",
    data: "22/09/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "cazetv"],
  },
  {
    timeCasa: "Atlético-MG",
    timeVisitante: "Mirassol",
    data: "28/09/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "band", "espn"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Bragantino",
    data: "02/10/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "disney-plus", "globo"],
  },
  {
    timeCasa: "Corinthians",
    timeVisitante: "Mirassol",
    data: "17/10/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["youtube", "sportv"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Mirassol",
    data: "27/10/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "espn"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "São Paulo",
    data: "06/11/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "premiere"],
  },
  {
    timeCasa: "Sport",
    timeVisitante: "Mirassol",
    data: "19/11/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "record"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Botafogo",
    data: "22/11/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "cazetv"],
  },
  {
    timeCasa: "Fluminense",
    timeVisitante: "Mirassol",
    data: "29/11/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["youtube", "tnt-sports"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Palmeiras",
    data: "03/12/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "record"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Mirassol",
    data: "06/12/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "goat"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Ceará",
    data: "11/12/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "band"],
  },
  {
    timeCasa: "Vitória",
    timeVisitante: "Mirassol",
    data: "14/12/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "sbt"],
  },
  {
    timeCasa: "Vasco",
    timeVisitante: "Mirassol",
    data: "18/12/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "cazetv"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Flamengo",
    data: "21/12/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["record", "disney-plus", "premiere"],
  },
];
