export const jogosTime = [
  {
    timeCasa: "Vasco",
    timeVisitante: "Santos",
    data: "29/03/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Bahia",
    data: "06/04/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "premiere"],
  },
  {
    timeCasa: "Fluminense",
    timeVisitante: "Santos",
    data: "13/04/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["band", "sportv"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Atlético-MG",
    data: "17/04/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["disney-plus", "paramount-plus"],
  },
  {
    timeCasa: "São Paulo",
    timeVisitante: "Santos",
    data: "20/04/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["record", "youtube"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Bragantino",
    data: "27/04/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports", "prime-video"],
  },
  {
    timeCasa: "Grêmio",
    timeVisitante: "Santos",
    data: "04/05/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "premiere", "sbt"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Ceará",
    data: "11/05/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["band", "sportv", "cazetv"],
  },
  {
    timeCasa: "Corinthians",
    timeVisitante: "Santos",
    data: "18/05/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["disney-plus", "paramount-plus", "goat"],
  },
  {
    timeCasa: "Vitória",
    timeVisitante: "Santos",
    data: "25/05/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["record", "youtube", "espn"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Botafogo",
    data: "01/06/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "prime-video", "globo"],
  },
  {
    timeCasa: "Fortaleza",
    timeVisitante: "Santos",
    data: "12/06/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["premiere", "sbt", "band"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Palmeiras",
    data: "13/07/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "cazetv", "disney-plus"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Flamengo",
    data: "17/07/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "goat", "record"],
  },
  {
    timeCasa: "Mirassol",
    timeVisitante: "Santos",
    data: "20/07/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["youtube", "espn", "tnt-sports"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Internacional",
    data: "24/07/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["prime-video", "globo", "premiere"],
  },
  {
    timeCasa: "Sport",
    timeVisitante: "Santos",
    data: "27/07/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "band", "sportv"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Juventude",
    data: "03/08/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["cazetv", "disney-plus", "paramount-plus"],
  },
  {
    timeCasa: "Cruzeiro",
    timeVisitante: "Santos",
    data: "10/08/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["goat", "record", "youtube"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Vasco",
    data: "17/08/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports", "prime-video"],
  },
  {
    timeCasa: "Bahia",
    timeVisitante: "Santos",
    data: "24/08/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "premiere", "sbt"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Fluminense",
    data: "31/08/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["band", "sportv", "cazetv"],
  },
  {
    timeCasa: "Atlético-MG",
    timeVisitante: "Santos",
    data: "14/09/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["disney-plus", "paramount-plus", "goat"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "São Paulo",
    data: "21/09/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["record", "youtube", "espn"],
  },
  {
    timeCasa: "Bragantino",
    timeVisitante: "Santos",
    data: "28/09/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["tnt-sports", "prime-video", "globo"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Grêmio",
    data: "02/10/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["premiere", "sbt", "band"],
  },
  {
    timeCasa: "Ceará",
    timeVisitante: "Santos",
    data: "17/10/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sportv", "cazetv", "disney-plus"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Corinthians",
    data: "26/10/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["paramount-plus", "goat", "record"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Vitória",
    data: "06/11/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["youtube", "espn", "tnt-sports"],
  },
  {
    timeCasa: "Botafogo",
    timeVisitante: "Santos",
    data: "20/11/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["prime-video", "globo", "premiere"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Fortaleza",
    data: "23/11/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["sbt", "band", "sportv"],
  },
  {
    timeCasa: "Palmeiras",
    timeVisitante: "Santos",
    data: "30/11/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["cazetv", "disney-plus", "paramount-plus"],
  },
  {
    timeCasa: "Flamengo",
    timeVisitante: "Santos",
    data: "04/12/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["goat", "record", "youtube"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Mirassol",
    data: "07/12/2025",
    horario: "18:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["espn", "tnt-sports", "prime-video"],
  },
  {
    timeCasa: "Internacional",
    timeVisitante: "Santos",
    data: "11/12/2025",
    horario: "16:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["globo", "premiere", "sbt"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Sport",
    data: "14/12/2025",
    horario: "21:45",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["band", "sportv", "cazetv"],
  },
  {
    timeCasa: "Juventude",
    timeVisitante: "Santos",
    data: "18/12/2025",
    horario: "19:00",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["disney-plus", "paramount-plus", "goat"],
  },
  {
    timeCasa: "Santos",
    timeVisitante: "Cruzeiro",
    data: "21/12/2025",
    horario: "20:30",
    campeonato: "Campeonato Brasileiro",
    transmissao: ["record", "youtube", "espn"],
  },
];
